// GENERATED by tools/gen_panel.py - do not edit, change the generator instead.
#pragma once

namespace tantra::panel {

constexpr int kTexW = 2048, kTexH = 2048, kPanelW = 1600, kPanelH = 520;
constexpr int kDisplayBg[3] = {10, 15, 13};
constexpr int kCellW = 11, kCellH = 20, kAtlasCols = 32;
enum Font { FONT_AMBER, FONT_GREEN, FONT_RED, FONT_WHITE };
constexpr int kFontOrigin[][2] = {{0, 540}, {0, 690}, {380, 540}, {380, 690}};
constexpr int kBigW = 24, kBigH = 40, kBigX = 1200, kBigY = 960;
constexpr char kBigChars[] = "0123456789.g -";
constexpr int kChW = 60, kChH = 210, kChX = 800, kChY = 740;
constexpr int kChTileX[4] = {36, 110, 184, 258}, kChTileY = 54;
constexpr int kKnobW = 50, kKnobH = 36, kKnobX = 800, kKnobY = 960;
constexpr int kLeverX[4] = {60, 132, 204, 276};
constexpr int kTrapX[4] = {372, 432, 492, 552}, kTrapY0 = 60, kTrapY1 = 270, kTrapW = 44;
constexpr int kRodX0 = 658, kRodW = 16, kRodGap = 8, kRodN = 10, kRodY0 = 146, kRodY1 = 246;
constexpr int kPaletteN = 20, kPaletteX = 0, kPaletteY = 1008;
constexpr int kPalette[kPaletteN][3] = {{10, 15, 13}, {0, 0, 0}, {255, 255, 255}, {22, 20, 18}, {30, 34, 32}, {30, 36, 34}, {50, 45, 38}, {90, 70, 40}, {120, 95, 50}, {120, 90, 40}, {60, 170, 90}, {190, 60, 45}, {80, 170, 110}, {80, 220, 120}, {110, 170, 230}, {230, 140, 40}, {200, 160, 70}, {80, 220, 70}, {190, 120, 255}, {230, 150, 60}};
enum PanelId { PANEL_MAIN = 0, PANEL_UPPER = 1, PANEL_LOWER = 2 };
struct PanelGeom { int texX, texY, w, h; };
constexpr PanelGeom kPanel[3] = {{0, 1040, 2040, 400}, {0, 0, 1600, 520}, {0, 1480, 1600, 440}};
constexpr int kMfdSY = 36, kMfdS = 320, kMfdBtnH = 32, kMfdBtnPitch = 50, kMfdBtnY0 = 14;
constexpr int kMfdUnit[4][2] = {{8, 2}, {428, 0}, {1200, 1}, {1620, 3}};  // x, MFD id
constexpr int kMimicW = 150, kMimicX = 1596, kMimicY = 560;
enum MimicPose { MIMIC_FLIGHT, MIMIC_LEVEL, MIMIC_LIFTED, MIMIC_TURN30, MIMIC_TURN60, MIMIC_VERTCOLS, MIMIC_STAND, MIMIC_PORT, MIMIC_LEGSOUT };

enum Area {
    A_CHAMBERS,
    A_LEVER,
    A_STOP,
    A_TRAPS,
    A_TRAPSEL,
    A_STORE,
    A_IONRODS,
    A_PLANT,
    A_COMP,
    A_GLIM,
    A_GSTEP,
    A_OVERRIDE,
    A_ALT,
    A_READOUT,
    A_AIRLOCK,
    A_EVA,
    A_CREWSEL,
    A_CREWINFO,
    A_SEL_PLAN,
    A_SEL_ANA,
    A_PODS_AFT,
    A_PODS_DOWN,
    A_PODS_IND,
    A_MSG,
    M_MFD2_L,
    M_MFD2_R,
    M_MFD2_B,
    M_MFD0_L,
    M_MFD0_R,
    M_MFD0_B,
    M_MFD1_L,
    M_MFD1_R,
    M_MFD1_B,
    M_MFD3_L,
    M_MFD3_R,
    M_MFD3_B,
    M_MSG,
    M_SEL_PLAN,
    M_SEL_ANA,
    M_START,
    M_STOP,
    M_THROTTLE,
    M_G,
    M_FLIGHT,
    M_GEAR,
    L_MIMIC,
    L_POSE,
    L_PHASE,
    L_PROG,
    L_GEAR,
    L_SET_LEVEL,
    L_SET_STAND,
    L_ERECT,
    L_PORT,
    L_LOADS,
    L_CRESTS,
    L_PODS_AFT,
    L_PODS_DOWN,
    L_PODS_IND,
    L_IRIS,
    L_HANGAR,
    L_ROVERS,
    L_DECK,
    L_AIRLOCK,
    L_EVA,
    L_CREWSEL,
    L_PT_LIFT,
    L_PT_LOAD,
    L_PT_DROP,
    L_PT_STOP,
    L_PT_ST,
    L_MSG,
    A_COUNT
};
// Area rectangles in panel coordinates (registration, mouse) and in texture coordinates (drawing).
constexpr int kAreaPanel[A_COUNT] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2};
constexpr int kAreaLocal[A_COUNT][4] = {
    {30, 50, 322, 268},  // CHAMBERS
    {24, 274, 328, 318},  // LEVER
    {24, 346, 328, 390},  // STOP
    {356, 50, 616, 300},  // TRAPS
    {356, 346, 616, 390},  // TRAPSEL
    {652, 50, 896, 108},  // STORE
    {652, 140, 896, 272},  // IONRODS
    {652, 290, 896, 390},  // PLANT
    {932, 50, 1192, 190},  // COMP
    {932, 200, 1192, 236},  // GLIM
    {932, 244, 1192, 280},  // GSTEP
    {932, 288, 1192, 324},  // OVERRIDE
    {932, 332, 1192, 390},  // ALT
    {1228, 50, 1576, 210},  // READOUT
    {1228, 222, 1398, 258},  // AIRLOCK
    {1406, 222, 1576, 258},  // EVA
    {1228, 266, 1576, 302},  // CREWSEL
    {1228, 310, 1576, 390},  // CREWINFO
    {150, 410, 390, 446},  // SEL_PLAN
    {398, 410, 638, 446},  // SEL_ANA
    {800, 410, 960, 446},  // PODS_AFT
    {968, 410, 1128, 446},  // PODS_DOWN
    {1136, 410, 1588, 446},  // PODS_IND
    {12, 480, 1588, 510},  // MSG
    {10, 36, 50, 356},  // M_MFD2_L
    {378, 36, 418, 356},  // M_MFD2_R
    {54, 362, 374, 392},  // M_MFD2_B
    {430, 36, 470, 356},  // M_MFD0_L
    {798, 36, 838, 356},  // M_MFD0_R
    {474, 362, 794, 392},  // M_MFD0_B
    {1202, 36, 1242, 356},  // M_MFD1_L
    {1570, 36, 1610, 356},  // M_MFD1_R
    {1246, 362, 1566, 392},  // M_MFD1_B
    {1622, 36, 1662, 356},  // M_MFD3_L
    {1990, 36, 2030, 356},  // M_MFD3_R
    {1666, 362, 1986, 392},  // M_MFD3_B
    {428, 6, 1612, 30},  // M_MSG
    {856, 36, 1016, 72},  // M_SEL_PLAN
    {1024, 36, 1184, 72},  // M_SEL_ANA
    {856, 80, 1016, 114},  // M_START
    {1024, 80, 1184, 114},  // M_STOP
    {856, 122, 1184, 180},  // M_THROTTLE
    {856, 188, 1184, 262},  // M_G
    {856, 270, 1184, 350},  // M_FLIGHT
    {856, 358, 1184, 392},  // M_GEAR
    {20, 40, 170, 190},  // L_MIMIC
    {180, 40, 332, 190},  // L_POSE
    {20, 198, 332, 230},  // L_PHASE
    {20, 238, 332, 262},  // L_PROG
    {364, 44, 688, 80},  // L_GEAR
    {364, 88, 522, 124},  // L_SET_LEVEL
    {530, 88, 688, 124},  // L_SET_STAND
    {364, 132, 688, 176},  // L_ERECT
    {364, 184, 688, 220},  // L_PORT
    {364, 228, 688, 382},  // L_LOADS
    {732, 44, 1008, 80},  // L_CRESTS
    {732, 88, 866, 124},  // L_PODS_AFT
    {874, 88, 1008, 124},  // L_PODS_DOWN
    {732, 132, 1008, 166},  // L_PODS_IND
    {732, 176, 1008, 262},  // L_IRIS
    {1052, 44, 1310, 80},  // L_HANGAR
    {1318, 44, 1576, 80},  // L_ROVERS
    {1052, 88, 1576, 150},  // L_DECK
    {1052, 158, 1310, 194},  // L_AIRLOCK
    {1318, 158, 1576, 194},  // L_EVA
    {1052, 202, 1576, 238},  // L_CREWSEL
    {1052, 256, 1310, 290},  // L_PT_LIFT
    {1318, 256, 1576, 290},  // L_PT_LOAD
    {1052, 298, 1310, 332},  // L_PT_DROP
    {1318, 298, 1576, 332},  // L_PT_STOP
    {1052, 340, 1576, 388},  // L_PT_ST
    {12, 400, 1588, 430},  // L_MSG
};
constexpr int kArea[A_COUNT][4] = {
    {30, 50, 322, 268},  // CHAMBERS
    {24, 274, 328, 318},  // LEVER
    {24, 346, 328, 390},  // STOP
    {356, 50, 616, 300},  // TRAPS
    {356, 346, 616, 390},  // TRAPSEL
    {652, 50, 896, 108},  // STORE
    {652, 140, 896, 272},  // IONRODS
    {652, 290, 896, 390},  // PLANT
    {932, 50, 1192, 190},  // COMP
    {932, 200, 1192, 236},  // GLIM
    {932, 244, 1192, 280},  // GSTEP
    {932, 288, 1192, 324},  // OVERRIDE
    {932, 332, 1192, 390},  // ALT
    {1228, 50, 1576, 210},  // READOUT
    {1228, 222, 1398, 258},  // AIRLOCK
    {1406, 222, 1576, 258},  // EVA
    {1228, 266, 1576, 302},  // CREWSEL
    {1228, 310, 1576, 390},  // CREWINFO
    {150, 410, 390, 446},  // SEL_PLAN
    {398, 410, 638, 446},  // SEL_ANA
    {800, 410, 960, 446},  // PODS_AFT
    {968, 410, 1128, 446},  // PODS_DOWN
    {1136, 410, 1588, 446},  // PODS_IND
    {12, 480, 1588, 510},  // MSG
    {10, 1076, 50, 1396},  // M_MFD2_L
    {378, 1076, 418, 1396},  // M_MFD2_R
    {54, 1402, 374, 1432},  // M_MFD2_B
    {430, 1076, 470, 1396},  // M_MFD0_L
    {798, 1076, 838, 1396},  // M_MFD0_R
    {474, 1402, 794, 1432},  // M_MFD0_B
    {1202, 1076, 1242, 1396},  // M_MFD1_L
    {1570, 1076, 1610, 1396},  // M_MFD1_R
    {1246, 1402, 1566, 1432},  // M_MFD1_B
    {1622, 1076, 1662, 1396},  // M_MFD3_L
    {1990, 1076, 2030, 1396},  // M_MFD3_R
    {1666, 1402, 1986, 1432},  // M_MFD3_B
    {428, 1046, 1612, 1070},  // M_MSG
    {856, 1076, 1016, 1112},  // M_SEL_PLAN
    {1024, 1076, 1184, 1112},  // M_SEL_ANA
    {856, 1120, 1016, 1154},  // M_START
    {1024, 1120, 1184, 1154},  // M_STOP
    {856, 1162, 1184, 1220},  // M_THROTTLE
    {856, 1228, 1184, 1302},  // M_G
    {856, 1310, 1184, 1390},  // M_FLIGHT
    {856, 1398, 1184, 1432},  // M_GEAR
    {20, 1520, 170, 1670},  // L_MIMIC
    {180, 1520, 332, 1670},  // L_POSE
    {20, 1678, 332, 1710},  // L_PHASE
    {20, 1718, 332, 1742},  // L_PROG
    {364, 1524, 688, 1560},  // L_GEAR
    {364, 1568, 522, 1604},  // L_SET_LEVEL
    {530, 1568, 688, 1604},  // L_SET_STAND
    {364, 1612, 688, 1656},  // L_ERECT
    {364, 1664, 688, 1700},  // L_PORT
    {364, 1708, 688, 1862},  // L_LOADS
    {732, 1524, 1008, 1560},  // L_CRESTS
    {732, 1568, 866, 1604},  // L_PODS_AFT
    {874, 1568, 1008, 1604},  // L_PODS_DOWN
    {732, 1612, 1008, 1646},  // L_PODS_IND
    {732, 1656, 1008, 1742},  // L_IRIS
    {1052, 1524, 1310, 1560},  // L_HANGAR
    {1318, 1524, 1576, 1560},  // L_ROVERS
    {1052, 1568, 1576, 1630},  // L_DECK
    {1052, 1638, 1310, 1674},  // L_AIRLOCK
    {1318, 1638, 1576, 1674},  // L_EVA
    {1052, 1682, 1576, 1718},  // L_CREWSEL
    {1052, 1736, 1310, 1770},  // L_PT_LIFT
    {1318, 1736, 1576, 1770},  // L_PT_LOAD
    {1052, 1778, 1310, 1812},  // L_PT_DROP
    {1318, 1778, 1576, 1812},  // L_PT_STOP
    {1052, 1820, 1576, 1868},  // L_PT_ST
    {12, 1880, 1588, 1910},  // L_MSG
};

}  // namespace tantra::panel
