// «Грань» 25,4 м: the pilots' cabin mesh LanderCabin.msh (the drum for two, layout v10). GENERATED by
// Tantra_Design/lander_mesh/gen_lander_cabin.py - do not edit. Orbiter frame (X right, Y up, Z forward), the hull mesh's origin.
#pragma once

namespace tantra::lander::cabin {

constexpr int kGroupCount = 50;
enum Grp { G_drum_wall = 0, G_drum_caps = 1, G_drum_hatch_rim = 2, G_drum_floor = 3, G_screen_frame = 4, G_pedestal = 5, G_mode_switch = 6, G_mode_pointer = 7, G_drum_supports = 8, G_drum_bearings = 9, G_couch_K = 10, G_insert_K = 11, G_roll_bearing_K = 12, G_yoke_K = 13, G_yoke_btn_K = 14, G_yoke_screen_K = 15, G_console_K = 16, G_levers_K = 17, G_lever_knob_K = 18, G_cursor_K = 19, G_panel_K = 20, G_panel_lip_K = 21, G_mfd_bezel_K = 22, G_mfd_0 = 23, G_mfd_btn_0 = 24, G_mfd_1 = 25, G_mfd_btn_1 = 26, G_ship_bezel_K = 27, G_ship_screen_K = 28, G_ship_keys_K = 29, G_couch_2 = 30, G_insert_2 = 31, G_roll_bearing_2 = 32, G_yoke_2 = 33, G_yoke_btn_2 = 34, G_yoke_screen_2 = 35, G_console_2 = 36, G_levers_2 = 37, G_lever_knob_2 = 38, G_cursor_2 = 39, G_panel_2 = 40, G_panel_lip_2 = 41, G_mfd_bezel_2 = 42, G_mfd_2 = 43, G_mfd_btn_2 = 44, G_mfd_3 = 45, G_mfd_btn_3 = 46, G_ship_bezel_2 = 47, G_ship_screen_2 = 48, G_ship_keys_2 = 49 };
// the drum turns about the lateral axis (Orbiter X) through kDrumC; the pilots' modules roll about Z through kRollRef[p]
constexpr double kDrumC[3] = {0.0000, 0.5500, 6.9500};
constexpr unsigned kDrumGroups[] = {G_drum_wall, G_drum_caps, G_drum_hatch_rim, G_drum_floor, G_screen_frame, G_pedestal, G_mode_switch, G_mode_pointer, G_roll_bearing_K, G_roll_bearing_2};
constexpr unsigned kModuleGroups[2][19] = {{G_couch_K, G_insert_K, G_yoke_K, G_yoke_btn_K, G_yoke_screen_K, G_console_K, G_levers_K, G_lever_knob_K, G_cursor_K, G_panel_K, G_panel_lip_K, G_mfd_bezel_K, G_ship_bezel_K, G_ship_screen_K, G_ship_keys_K, G_mfd_0, G_mfd_btn_0, G_mfd_1, G_mfd_btn_1}, {G_couch_2, G_insert_2, G_yoke_2, G_yoke_btn_2, G_yoke_screen_2, G_console_2, G_levers_2, G_lever_knob_2, G_cursor_2, G_panel_2, G_panel_lip_2, G_mfd_bezel_2, G_mfd_2, G_mfd_btn_2, G_ship_bezel_2, G_ship_screen_2, G_ship_keys_2, G_mfd_3, G_mfd_btn_3}};
constexpr int kModuleCount[2] = {19, 19};
constexpr double kRollRef[2][3] = {{-0.6200, 0.6700, 6.8000}, {0.6200, 0.6700, 6.8000}};
// the pilots (0 commander left, 1 second pilot right): the eyes (the camera), the default look (forward, 17° up)
constexpr double kEye[2][3] = {{-0.6200, 0.5800, 6.3600}, {0.6200, 0.5800, 6.3600}};
constexpr double kLook[2][3] = {{0.1000, 0.2924, 0.9511}, {-0.1000, 0.2924, 0.9511}};
constexpr double kHub[2][3] = {{-0.6200, 0.5200, 6.9803}, {0.6200, 0.5200, 6.9803}};
constexpr double kMode[3] = {0.0000, 0.2000, 6.6600};   // the mode switch on the pedestal
// the Orbiter MFDs 0..3 (commander НАВ-1, НАВ-2, second pilot НАВ-1, НАВ-2): the screen group and the click quads
// (top-left, top-right, bottom-left, bottom-right): the left buttons 0..5, the right 6..11, the bottom PWR SEL MNU
constexpr int kMfdGroup[4] = {G_mfd_0, G_mfd_1, G_mfd_2, G_mfd_3};
constexpr int kMfdBtnGroup[4] = {G_mfd_btn_0, G_mfd_btn_1, G_mfd_btn_2, G_mfd_btn_3};
constexpr double kMfdLeft[4][4][3] = {{{-1.0770, 0.7174, 6.7512}, {-1.0442, 0.7174, 6.7741}, {-1.0809, 0.5235, 6.7567}, {-1.0481, 0.5235, 6.7797}}, {{-1.1949, 0.7167, 6.4518}, {-1.1787, 0.7167, 6.4883}, {-1.2011, 0.5228, 6.4545}, {-1.1849, 0.5228, 6.4911}}, {{0.8313, 0.7174, 6.9232}, {0.8640, 0.7174, 6.9003}, {0.8352, 0.5235, 6.9288}, {0.8679, 0.5235, 6.9058}}, {{1.0729, 0.7167, 6.7259}, {1.0892, 0.7167, 6.6893}, {1.0791, 0.5228, 6.7286}, {1.0954, 0.5228, 6.6921}}};
constexpr double kMfdRight[4][4][3] = {{{-0.8640, 0.7174, 6.9003}, {-0.8313, 0.7174, 6.9232}, {-0.8679, 0.5235, 6.9058}, {-0.8352, 0.5235, 6.9288}}, {{-1.0892, 0.7167, 6.6893}, {-1.0729, 0.7167, 6.7259}, {-1.0954, 0.5228, 6.6921}, {-1.0791, 0.5228, 6.7286}}, {{1.0442, 0.7174, 6.7741}, {1.0770, 0.7174, 6.7512}, {1.0481, 0.5235, 6.7797}, {1.0809, 0.5235, 6.7567}}, {{1.1787, 0.7167, 6.4883}, {1.1949, 0.7167, 6.4518}, {1.1849, 0.5228, 6.4911}, {1.2011, 0.5228, 6.4545}}};
constexpr double kMfdBottom[4][4][3] = {{{-1.0284, 0.4856, 6.7951}, {-0.8892, 0.4856, 6.8926}, {-1.0288, 0.4656, 6.7957}, {-0.8896, 0.4656, 6.8932}}, {{-1.1759, 0.4849, 6.5145}, {-1.1068, 0.4849, 6.6698}, {-1.1765, 0.4649, 6.5147}, {-1.1074, 0.4649, 6.6700}}, {{0.8892, 0.4856, 6.8926}, {1.0284, 0.4856, 6.7951}, {0.8896, 0.4656, 6.8932}, {1.0288, 0.4656, 6.7957}}, {{1.1068, 0.4849, 6.6698}, {1.1759, 0.4849, 6.5145}, {1.1074, 0.4649, 6.6700}, {1.1765, 0.4649, 6.5147}}};
// the button labels' texture cab_lbl (dynamic, mesh texture 3): 512 × 256, cells 64 × 32, MFD m button b -> cell m·15 + b
constexpr int kLblTex = 3, kLblW = 512, kLblH = 256, kLblCW = 64, kLblCH = 32;
// the ships' MFDs (0 commander, 1 second pilot): the screen and the key columns (keys 0..5 left, 6..11 right) as click quads
constexpr int kShipScreenGroup[2] = {G_ship_screen_K, G_ship_screen_2};
constexpr double kShipScreen[2][4][3] = {{{-0.3319, 0.6904, 6.9041}, {-0.1089, 0.6904, 6.7034}, {-0.3296, 0.4905, 6.9067}, {-0.1066, 0.4905, 6.7060}}, {{0.1089, 0.6904, 6.7034}, {0.3319, 0.6904, 6.9041}, {0.1066, 0.4905, 6.7060}, {0.3296, 0.4905, 6.9067}}};
constexpr double kShipLeft[2][4][3] = {{{-0.3733, 0.6872, 6.9254}, {-0.3436, 0.6872, 6.8986}, {-0.3711, 0.4933, 6.9279}, {-0.3413, 0.4933, 6.9011}}, {{0.0835, 0.6872, 6.6644}, {0.1132, 0.6872, 6.6912}, {0.0812, 0.4933, 6.6669}, {0.1110, 0.4933, 6.6937}}};
constexpr double kShipRight[2][4][3] = {{{-0.1132, 0.6872, 6.6912}, {-0.0835, 0.6872, 6.6644}, {-0.1110, 0.4933, 6.6937}, {-0.0812, 0.4933, 6.6669}}, {{0.3436, 0.6872, 6.8986}, {0.3733, 0.6872, 6.9254}, {0.3413, 0.4933, 6.9011}, {0.3711, 0.4933, 6.9279}}};
// their texture cab_ship (dynamic, mesh texture 4): 1024 × 512; pilot p's screen at x p·512, 512 × 340; key k's cell
// at x p·512 + (k mod 8)·64, y 352 + (k div 8)·40, 64 × 32
constexpr int kShipTex = 4, kShipW = 1024, kShipH = 512, kShipScrW = 512, kShipScrH = 340;
// OrbiterCrew (the person inside, as in «Тантра»): each Orbiter MFD's screen has its own texture slot - ShipView's
// MfdBank binds the MFD's surface there; the screens' corners (top-left, top-right, bottom-left, bottom-right)
constexpr int kMfdTex[4] = {5, 6, 7, 8};
constexpr double kMfdScreen[4][4][3] = {{{-1.0469, 0.7258, 6.7866}, {-0.8748, 0.7258, 6.9070}, {-1.0511, 0.5160, 6.7926}, {-0.8791, 0.5160, 6.9130}}, {{-1.1873, 0.7251, 6.4977}, {-1.1019, 0.7251, 6.6895}, {-1.1940, 0.5153, 6.5006}, {-1.1086, 0.5153, 6.6925}}, {{0.8748, 0.7258, 6.9070}, {1.0469, 0.7258, 6.7866}, {0.8791, 0.5160, 6.9130}, {1.0511, 0.5160, 6.7926}}, {{1.1019, 0.7251, 6.6895}, {1.1873, 0.7251, 6.4977}, {1.1086, 0.5153, 6.6925}, {1.1940, 0.5153, 6.5006}}};
// the seats: the hips (stature 1,74, the couch at its middle) and the facing (+Z); the hands' targets: the inboard
// yoke grip (its two ends), the hub and a point 1 m on toward the eye (the hub's facing), the МАРШ knob
constexpr double kHip[2][3] = {{-0.6200, 0.0570, 6.8433}, {0.6200, 0.0570, 6.8433}};
constexpr double kGrip[2][2][3] = {{{-0.4600, 0.4603, 6.9745}, {-0.4300, 0.3607, 6.9649}}, {{0.4600, 0.4603, 6.9745}, {0.4300, 0.3607, 6.9649}}};
constexpr double kHubN[2][3] = {{-0.6200, 0.6163, 5.9849}, {0.6200, 0.6163, 5.9849}};
constexpr double kMarch[2][3] = {{-1.0300, 0.2450, 6.9350}, {1.0300, 0.2450, 6.9350}};
constexpr double kDrumFloorY = -0.4500, kDrumHatch[3] = {-1.5000, 0.5500, 6.9500}, kDrumHatchR = 0.42;   // the drum's floor; its axial hatch (left end)

}  // namespace tantra::lander::cabin
