# -*- coding: utf-8 -*-
"""Заголовок модуля Orbiter «Грани» из out/lander_mesh.json (меш 25,4 м): номера групп, анимации, шасси, чаши, маршевые,
сопла ориентации, аэродинамика. Запуск: python gen_lander_header.py -> Orbitersdk/samples/TantraLander/orbiter/LanderMesh.h

Система Orbiter левая: X вправо, Y вверх, Z вперёд = (z, y, x) спецификации. Перестановка x<->z - отражение, поэтому угол
поворота анимации меняет знак (ось переставляется так же): S·R(a, θ)·S = R(S·a, −θ).
"""
import json, os, math
import numpy as np
from shapely.geometry import Polygon
from shapely.ops import unary_union

HERE = os.path.dirname(os.path.abspath(__file__))
D = json.load(open(os.path.join(HERE, "out", "lander_mesh.json"), encoding="utf-8"))
OUT = os.path.join(HERE, "..", "..", "Orbitersdk", "samples", "TantraLander", "orbiter", "LanderMesh.h")
SC = D["scale"]; K = SC["K"]
G = {g["name"]: g for g in D["groups"]}
NAMES = [g["name"] for g in D["groups"]]
MODES = D["modes"]

def O(p):        # spec -> Orbiter
    return (p[2], p[1], p[0])
def V3(p):
    return "{%.4f, %.4f, %.4f}" % tuple(p)
def verts(name):
    return np.array(G[name]["v"], float).reshape(-1, 3)
def tris(name):
    V = verts(name); I = np.array(G[name]["i"]).reshape(-1, 3)
    return V[I[:, 0]], V[I[:, 1]], V[I[:, 2]]

L = []
L.append("// «Грань» 25,4 м: the mesh contract of Lander.msh for the Orbiter module. GENERATED by")
L.append("// Tantra_Design/lander_mesh/gen_lander_header.py from out/lander_mesh.json - do not edit. Orbiter frame: X right, Y up,")
L.append("// Z forward (left-handed) = spec (z, y, x); origin = the mesh origin (= TLANDER); animation angles already in Orbiter's sense.")
L.append("#pragma once")
L.append("")
L.append("namespace tantra::lander::mesh {")
L.append("")
L.append("constexpr double kScale = %.4f;                  // Т1Б-А ×K" % K)
L.append("constexpr int kGroupCount = %d;" % len(NAMES))
L.append("enum Grp {")
L.append("    " + ", ".join("G_%s = %d" % (n, i) for i, n in enumerate(NAMES)))
L.append("};")
L.append("")

# ---------------------------------------------------------------- animations
AN = [("tipL", "концевая часть Л"), ("tipR", "концевая часть П"), ("elevL", "элевон Л"), ("elevR", "элевон П"),
      ("marchL", "УВТ маршевого L"), ("marchR", "УВТ маршевого R"), ("rowF", "ряд чаш P"), ("rowR", "ряд чаш Z"),
      ("panelF", "створка ряда P"), ("panelR", "створка ряда Z"), ("flap", "щиток днища"), ("gearN", "ПО, уборка вперёд"),
      ("gearL", "основная L, уборка вперёд"), ("gearR", "основная R, уборка вперёд"), ("doorN", "створка-полоз ПО"),
      ("doorL", "створка-полоз L"), ("doorR", "створка-полоз R"), ("hatch", "люк"), ("fin", "киль"),
      ("doorN2", "внутренняя створка-полоз ПО"), ("doorL2", "внутренняя створка-полоз L"), ("doorR2", "внутренняя створка-полоз R")]
byNote = {}
for e in D["anim"]:
    for key, pre in AN:
        if e["note"].startswith(pre):
            byNote[key] = e
assert len(byNote) == len(AN), set(k for k, _ in AN) - set(byNote)
L.append("// animations: the mesh pose is the spec angle 0 (state (0 − lo)/(hi − lo)); deg per mesh mode in MODES order")
L.append("// (%s); angle = spec degrees, the Orbiter rotation uses −angle (left-handed frame)" % ", ".join(MODES))
L.append("enum ModeMesh { " + ", ".join("MM_%s" % m for m in MODES) + ", kModeMesh };")
L.append("struct AnimDef { const char* key; int n; int grp[4]; double ref[3]; double axis[3]; double lo, hi; double mode[%d]; };" % len(MODES))
L.append("enum AnimId { " + ", ".join("A_%s" % k for k, _ in AN) + ", kAnimCount };")
L.append("constexpr AnimDef kAnim[kAnimCount] = {")
for key, _ in AN:
    e = byNote[key]
    g = [NAMES.index(n) for n in e["groups"]] + [-1] * (4 - len(e["groups"]))
    ax = np.array(O(e["axis"]), float); ax /= np.linalg.norm(ax)
    L.append('    {"%s", %d, {%s}, %s, %s, %g, %g, {%s}},' % (key, len(e["groups"]), ", ".join(map(str, g)), V3(O(e["pivot"])), V3(ax),
                                                         e["limits"][0], e["limits"][1], ", ".join("%g" % e["modes"].get(m, 0) for m in MODES)))
L.append("};")
L.append("")

# ---------------------------------------------------------------- gear (extended = mesh pose), shock travel
L.append("// gear: the wheel's lowest point (extended, unloaded), the strut's travel (GEAR.md: ход 0,85 + обжатие 0,10, ×K)")
L.append("struct GearDef { const char* key; double contact[3]; double stroke; int shtok, kolesa; };")
L.append("constexpr GearDef kGear[3] = {")
for s in "NLR":
    W = verts("shassi_%s_kolesa" % s)
    y0 = W[:, 1].min(); low = W[W[:, 1] < y0 + 0.02]
    c = (low[:, 0].mean(), y0, low[:, 2].mean())
    L.append('    {"%s", %s, %.4f, G_shassi_%s_shtok, G_shassi_%s_kolesa},' % (s, V3(O(c)), 0.95 * K, s, s))
L.append("};")
L.append("")

# ---------------------------------------------------------------- lift cups (deployed = mesh pose), marches
def cups(row):
    V = verts("ryad_%s_chashi" % row)
    zs = np.sort(np.unique(np.round(V[:, 2], 1)))
    out = []
    for zc in (-1.5 * K, 0.0, 1.5 * K):
        m = np.abs(V[:, 2] - zc) < 0.75 * K
        P = V[m]
        out.append((P[:, 0].mean(), P[:, 1].min(), zc))
    return out
rear, front = cups("Z"), cups("P")
L.append("// the lift cups' exits, in the core's unit order 2..7: the rear row (u.x = −kLiftX) z −, 0, +; then the front row")
L.append("constexpr double kCup[6][3] = {" + ", ".join(V3(O(p)) for p in rear + front) + "};")
ex = []
for s in "LR":
    V = verts("marsh_%s_srez" % s)
    ex.append((V[:, 0].min(), V[:, 1].mean(), V[:, 2].mean()))
L.append("constexpr double kMarchExit[2][3] = {" + ", ".join(V3(O(p)) for p in ex) + "};   // left (unit 0), right (unit 1)")
L.append("")

# ---------------------------------------------------------------- RCS
L.append("struct RcsDef { const char* id; double pos[3]; double exhaust[3]; };")
L.append("constexpr int kRcsCount = %d;" % len(D["rcs"]))
L.append("constexpr RcsDef kRcs[kRcsCount] = {")
for r in D["rcs"]:
    L.append('    {"%s", %s, %s},' % (r["id"], V3(O(r["pos"])), V3(O(r["exhaust_dir"]))))
L.append("};")
L.append("")

# ---------------------------------------------------------------- aero
A = D["aero"]; al = A["alphas"]
def plan_down(names):
    P = []; area = 0.0; cx = 0.0; cz = 0.0
    for n in names:
        a, b, c = tris(n); na = 0.5 * np.cross(b - a, c - a)
        dn = np.clip(-na[:, 1], 0, None); cen = (a + b + c) / 3
        area += dn.sum(); cx += (dn * cen[:, 0]).sum(); cz += (dn * np.abs(cen[:, 2])).sum()
        for i in np.where(dn > 1e-9)[0]:
            p = Polygon([(a[i, 0], a[i, 2]), (b[i, 0], b[i, 2]), (c[i, 0], c[i, 2])])
            if p.area > 1e-9: P.append(p.buffer(1e-6))
    return area, cx / max(area, 1e-9), cz / max(area, 1e-9), unary_union(P) if P else None
_, _, _, U = plan_down(["korpus", "dnische_tzp", "nos_poristy", "krylo_L", "krylo_R", "konc_L", "konc_R", "elevon_L", "elevon_R"])
x_ac = U.centroid.x
y_ac = 0.0
x_ref = -2.44 * K                                    # gen_lander newton(): cg = X_CG_E (−2,44 базовой формы, ×K)
L.append("// aerodynamics (gen_lander.py by the mesh, similarity: coefficients unchanged, S ×K², L ×K)")
L.append("constexpr double kSref = %.3f, kLref = %.4f;   // S_REF, L_REF ×K" % (SC["S_REF"], SC["L_REF"]))
L.append("constexpr double kXref = %.4f;                 // Z of the hypersonic tables' moment reference (X_CG_E ×K)" % x_ref)
L.append("constexpr double kSplan = %.2f;                // planform by the contour (union of the projected faces)" % U.area)
L.append("constexpr double kXacSub = %.4f;               // Z of the planform centroid = the subsonic aerodynamic centre (допущение)" % x_ac)
sp = A["sub_params"]
L.append("constexpr double kKp = %.5f, kKv = %.5f, kCD0 = %.4f;   // Polhamus (rounded edge), CD0" % (sp["Kp"], sp["Kv"], sp["CD0"]))
L.append("constexpr int kNa = %d;" % len(al))
L.append("constexpr double kAlpha[kNa] = {" + ", ".join("%g" % a for a in al) + "};")
L.append("// Newton tables, elevons 0: [tips 0 / 60 / 90][alpha] = {CL, CD, Cm about kXref}")
L.append("constexpr double kHyp[3][kNa][3] = {")
for t in (0, 60, 90):
    rows = A["hyp"]["t%d_e0" % t]
    L.append("    {" + ", ".join("{%.5f, %.5f, %.6f}" % (r[0], r[1], r[2]) for r in rows) + "},")
L.append("};")
xa = A["ext_alphas"]; xt = A["ext"]["t60_e0"]
L.append("constexpr int kNx = %d;" % len(xa))
L.append("constexpr double kExtAlpha[kNx] = {" + ", ".join("%g" % a for a in xa) + "};")
L.append("constexpr double kExt60[kNx][3] = {" + ", ".join("{%.5f, %.5f, %.6f}" % (r[0], r[1], r[2]) for r in xt) + "};   // −20…180°, tips 60")
FL = A["n3"]["flap"]
fls = sorted(int(k[2:]) for k in FL)
L.append("constexpr int kNfl = %d;" % len(fls))
L.append("constexpr double kFlapDeg[kNfl] = {" + ", ".join("%d" % f for f in fls) + "};")
base = np.array(FL["fl0"]["Cm"])
L.append("constexpr double kFlapDCm[kNfl][kNa] = {" + ", ".join("{" + ", ".join("%.5f" % v for v in (np.array(FL["fl%d" % f]["Cm"]) - base)) + "}" for f in fls) + "};")
# control surfaces
aE, xE, zE, _ = plan_down(["elevon_L"])
aF, xF, _, _ = plan_down(["schitok"])
yE = verts("elevon_L")[:, 1].mean(); yF = verts("schitok")[:, 1].mean()
L.append("constexpr double kElevonArea = %.3f, kElevonPos[3] = %s;   // one elevon (left; right mirrored X)" % (aE, V3(O((xE, yE, -zE)))))
L.append("constexpr double kFlapArea = %.3f, kFlapPos[3] = %s;" % (aF, V3(O((xF, yF, 0.0)))))
# fin: area, MAC quarter point
KF = SC["kil"]
cr, ct, H = KF["root_m"], KF["tip_m"], KF["H_m"]
lam = ct / cr; mac = 2.0 / 3.0 * cr * (1 + lam + lam * lam) / (1 + lam)
ymac = H / 3.0 * (1 + 2 * lam) / (1 + lam)
xle_root = KF["pivot"][0]; xle_mac = xle_root - ymac * math.tan(math.radians(20.0))
yroot = KF["pivot"][1]
L.append("constexpr double kFinArea = %.3f, kFinMac = %.3f, kFinAc[3] = %s;   // quarter MAC; folded in the hangar" %
         (KF["S_m2"], mac, V3(O((xle_mac - 0.25 * mac, yroot + ymac, 0.0)))))
L.append("constexpr double kFinFoldTime = 8.0;              // s (допущение)")
# hull touch points (belly landing, rollover): the lowest/outermost vertices by station
hull = verts("korpus"); belly = verts("dnische_tzp"); wing = np.vstack([verts("krylo_L"), verts("krylo_R")])
pts = []
allv = np.vstack([hull, belly])
xmin, xmax = allv[:, 0].min(), allv[:, 0].max()
for xs in np.linspace(xmin + 0.3, xmax - 0.6, 6):
    m = np.abs(allv[:, 0] - xs) < 0.6
    P = allv[m]
    lo = P[np.argmin(P[:, 1])]; pts.append((xs, lo[1], 0.0))
    top = P[np.argmax(P[:, 1])]; pts.append((xs, top[1], 0.0))
    for sgn in (-1, 1):
        q = P[np.argmax(sgn * P[:, 2])]; pts.append((xs, q[1], q[2]))
tipi = np.argmax(np.abs(wing[:, 2])); wt = wing[tipi]
pts += [(wt[0], wt[1], abs(wt[2])), (wt[0], wt[1], -abs(wt[2]))]
nose = allv[np.argmax(allv[:, 0])]; pts.append(tuple(nose))
L.append("constexpr int kHullPtCount = %d;   // belly, top, sides by station; wing tips; nose" % len(pts))
L.append("constexpr double kHullPt[kHullPtCount][3] = {" + ", ".join(V3(O(p)) for p in pts) + "};")
bb = SC["by_mode"]
L.append("constexpr double kLength = %.3f, kSpan = %.3f;" % (bb["glide"]["L"], bb["glide"]["W"]))
L.append("constexpr double kBellyMinY = %.4f;   // the belly's lowest point (the cradle's TLANDER contact, gear up)" % verts("dnische_tzp")[:, 1].min())
L.append("")
L.append("}  // namespace tantra::lander::mesh")
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
print("ok", OUT, "x_ac %.3f S_plan %.1f elevon %.2f m² flap %.2f m² fin mac %.2f" % (x_ac, U.area, aE, aF, mac))
print("cups rear", [tuple(round(c, 3) for c in O(p)) for p in rear]); print("cups front", [tuple(round(c, 3) for c in O(p)) for p in front])
print("march exits", [tuple(round(c, 3) for c in O(p)) for p in ex])
